name: Deploy docker images

on:
  push:
    branches:
      - 'docker'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # not email
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          # https://docs.docker.com/docker-hub/access-tokens/
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: TIMESCALEDB_APACHE_ONLY=false
          # context: ./postgres-appliance
          context: "{{defaultContext}}:postgres-appliance"
          push: true
          tags: cdmikechen/spilo-15:3.2-p1-tslicense-tstool-arm
          platforms: linux/arm64